name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  go:
    name: Build (go)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Build
      working-directory: service
      run: |
        go version
        GOOS=linux GOARCH=amd64 go build -o build/ivory

#     - name: Test
#       run: go test

  javascript:
    name: Build (javascript)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JavaScript
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Build
      working-directory: web
      run: |
        node -v
        yarn version
        yarn install
        yarn run build

#     - name: Test
#       run: yarn test
