name: Realease Docker Image

on:
  release:
    

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    # fetch repository
    - uses: actions/checkout@v2
    # setup go
    - uses: actions/setup-go@v2.1.5
      with:
        go-version: '1.17'
    # setup node (yarn, npm)
    - uses: actions/setup-node@v2.5.1
      with:
        node-version: '16'
        
    - run: echo ${{ env.RELEASE_VERSION }}
      
    - name: Install & Build web
      working-directory: web
      run: |
        node -v
        yarn version
        yarn install
        yarn run build
      
    - name: Intall & Build binary for service
      working-directory: service
      run: |
        go version
        GOOS=linux GOARCH=amd64 go build -o build
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ivory:$(date +%s)
    
    
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: publish
      run: echo 'publishing'
