name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.5
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
      
    - name: Build npm
      run: npm --prefix web run build
      
    - name: Build go binary
      run: GOOS=linux GOARCH=amd64 go build -o build
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ivory:$(date +%s)
