name: Release

on:
  release:
    types: [released]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: production
    steps:

      # Set up environment
      - name: Checkout & fetch repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up GO
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Set up Node (yarn, npm)
        uses: actions/setup-node@v3
        with:
          node-version: '16'


      # Build service
      - name: Install & Build web
        working-directory: web
        run: |
          node -v
          yarn version
          yarn install
          yarn run build

      - name: Install & Build binary for service
        working-directory: service
        run: |
          go version
          make build
      

      # Publish docker
      - name: Login to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push docker
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            aelsergeev/ivory:latest
            aelsergeev/ivory:${{ github.event.release.tag_name }}
            ghcr.io/veegres/ivory:latest
            ghcr.io/veegres/ivory:${{ github.event.release.tag_name }}
